# Generated by Django 4.2 on 2023-05-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osoba',
            name='prijmeni',
            field=models.CharField(help_text='Zadejte příjmení', max_length=45, verbose_name='Přijmení'),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='reputace',
            field=models.CharField(help_text='Zadejte reputaci', max_length=10, verbose_name='Reputatace'),
        ),
    ]
