# Generated by Django 4.2.1 on 2023-06-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_osoba_prijmeni_alter_osoba_reputace'),
    ]

    operations = [
        migrations.AddField(
            model_name='nemovitost',
            name='typ',
            field=models.CharField(choices=[('BYT', 'byt'), ('DŮM', 'dům')], default='BYT', help_text='Vyberte typ nemovitosti', max_length=45, verbose_name='Typ'),
        ),
        migrations.AddField(
            model_name='nemovitost',
            name='velikost',
            field=models.CharField(choices=[('1', '1'), ('1+1', '1+1'), ('2', '2'), ('2+1', '2+1'), ('3', '3'), ('3+1', '3+1')], default='1', help_text='Vyberte velikost nemovitosti', max_length=45, verbose_name='Velikost'),
        ),
    ]
