# Generated by Django 4.2.1 on 2023-06-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_nemovitost_typ_nemovitost_velikost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nemovitost',
            name='typ',
            field=models.CharField(choices=[('Byt', 'byt'), ('Dům', 'dům')], default='Byt', help_text='Vyberte typ nemovitosti', max_length=45, verbose_name='Typ'),
        ),
    ]
