# Generated by Django 4.2.1 on 2023-06-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_nemovitost_typ'),
    ]

    operations = [
        migrations.AddField(
            model_name='osoba',
            name='fotka',
            field=models.ImageField(default='none', help_text='Nahrejte fotku osoby', upload_to='osoba', verbose_name='Fotka osoby'),
        ),
    ]
